//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: Option<String>,
    pub discount_type: Option<i32>,
    pub discount_value: Option<Decimal>,
    pub minimum_amount: Option<Decimal>,
    pub maximum_discount: Option<Decimal>,
    pub usage_limit: Option<i32>,
    pub used_count: Option<i32>,
    pub expires_at: Option<DateTime>,
    pub active: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::coupon_usages::Entity")]
    CouponUsages,
}

impl Related<super::coupon_usages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponUsages.def()
    }
}
