//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "gateway_customers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub payment_gateway_id: i32,
    pub external_customer_id: String,
    pub status: i16,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_gateways::Entity",
        from = "Column::PaymentGatewayId",
        to = "super::payment_gateways::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentGateways,
    #[sea_orm(has_many = "super::payment_sources::Entity")]
    PaymentSources,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::payment_gateways::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGateways.def()
    }
}

impl Related<super::payment_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSources.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
