//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub order_number: Option<String>,
    pub status: Option<i32>,
    pub total_amount: Option<Decimal>,
    pub subtotal: Option<Decimal>,
    pub tax_amount: Option<Decimal>,
    pub shipping_amount: Option<Decimal>,
    pub discount_amount: Option<Decimal>,
    pub currency: Option<String>,
    pub payment_status: Option<i32>,
    pub fulfillment_status: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::coupon_usages::Entity")]
    CouponUsages,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::payments::Entity")]
    Payments,
    #[sea_orm(has_many = "super::shipments::Entity")]
    Shipments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::coupon_usages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponUsages.def()
    }
}

impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderItems.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}

impl Related<super::shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shipments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
