//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_method_countries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub payment_method_id: i32,
    pub country_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentMethods,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}
