//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_refunds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub payment_id: i32,
    pub amount: Decimal,
    pub currency: String,
    pub status: i16,
    pub reason: Option<i16>,
    pub external_refund_id: Option<String>,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    pub failure_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_message: Option<String>,
    pub processed_at: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payments::Entity",
        from = "Column::PaymentId",
        to = "super::payments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Payments,
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}
