//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_setup_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub payment_method_id: i32,
    pub payment_source_id: Option<i32>,
    pub status: i16,
    pub external_setup_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_client_secret: Option<String>,
    pub expires_at: Option<DateTime>,
    pub completed_at: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::payment_sources::Entity",
        from = "Column::PaymentSourceId",
        to = "super::payment_sources::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PaymentSources,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::payment_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSources.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
