//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_gateway_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub payment_id: Option<i32>,
    pub payment_session_id: Option<i32>,
    pub payment_gateway_event_id: Option<i32>,
    pub direction: i16,
    pub level: i16,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub payload: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_gateway_events::Entity",
        from = "Column::PaymentGatewayEventId",
        to = "super::payment_gateway_events::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PaymentGatewayEvents,
    #[sea_orm(
        belongs_to = "super::payment_sessions::Entity",
        from = "Column::PaymentSessionId",
        to = "super::payment_sessions::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PaymentSessions,
    #[sea_orm(
        belongs_to = "super::payments::Entity",
        from = "Column::PaymentId",
        to = "super::payments::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Payments,
}

impl Related<super::payment_gateway_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGatewayEvents.def()
    }
}

impl Related<super::payment_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSessions.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}
