//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub payment_id: i32,
    pub payment_method_id: i32,
    pub status: i16,
    pub external_session_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_client_secret: Option<String>,
    pub expires_at: Option<DateTime>,
    pub completed_at: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::payment_gateway_logs::Entity")]
    PaymentGatewayLogs,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::payments::Entity",
        from = "Column::PaymentId",
        to = "super::payments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Payments,
}

impl Related<super::payment_gateway_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGatewayLogs.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}
