//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_gateways")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub driver: String,
    pub environment: i16,
    pub status: i16,
    pub supports_authorize: bool,
    pub supports_capture: bool,
    pub supports_refund: bool,
    pub supports_void: bool,
    pub supports_saved_sources: bool,
    pub public_key_env: Option<String>,
    pub secret_key_env: Option<String>,
    pub webhook_secret_env: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gateway_customers::Entity")]
    GatewayCustomers,
    #[sea_orm(has_many = "super::payment_gateway_events::Entity")]
    PaymentGatewayEvents,
    #[sea_orm(has_many = "super::payment_methods::Entity")]
    PaymentMethods,
}

impl Related<super::gateway_customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GatewayCustomers.def()
    }
}

impl Related<super::payment_gateway_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGatewayEvents.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}
