//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub amount: Option<Decimal>,
    pub currency: Option<String>,
    pub status: Option<i32>,
    pub transaction_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gateway_response: Option<String>,
    pub processed_at: Option<DateTime>,
    pub order_id: i32,
    pub payment_method_id: i32,
    #[sea_orm(unique)]
    pub number: Option<String>,
    pub payment_source_id: Option<i32>,
    pub intent: i16,
    pub external_payment_id: Option<String>,
    pub external_status: Option<String>,
    #[sea_orm(unique)]
    pub idempotency_key: Option<String>,
    pub failure_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_message: Option<String>,
    pub authorized_at: Option<DateTime>,
    pub captured_at: Option<DateTime>,
    pub voided_at: Option<DateTime>,
    pub cancelled_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Orders,
    #[sea_orm(has_many = "super::payment_gateway_logs::Entity")]
    PaymentGatewayLogs,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::payment_refunds::Entity")]
    PaymentRefunds,
    #[sea_orm(has_many = "super::payment_sessions::Entity")]
    PaymentSessions,
    #[sea_orm(
        belongs_to = "super::payment_sources::Entity",
        from = "Column::PaymentSourceId",
        to = "super::payment_sources::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    PaymentSources,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::payment_gateway_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGatewayLogs.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::payment_refunds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentRefunds.def()
    }
}

impl Related<super::payment_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSessions.def()
    }
}

impl Related<super::payment_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSources.def()
    }
}
