//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_gateway_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub payment_gateway_id: i32,
    pub event_type: String,
    pub external_event_id: String,
    pub status: i16,
    pub signature_valid: bool,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub processed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_message: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::payment_gateway_logs::Entity")]
    PaymentGatewayLogs,
    #[sea_orm(
        belongs_to = "super::payment_gateways::Entity",
        from = "Column::PaymentGatewayId",
        to = "super::payment_gateways::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PaymentGateways,
}

impl Related<super::payment_gateway_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGatewayLogs.def()
    }
}

impl Related<super::payment_gateways::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentGateways.def()
    }
}
