//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_sources")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub payment_method_id: i32,
    pub gateway_customer_id: Option<i32>,
    pub source_type: i16,
    pub external_source_id: String,
    pub brand: Option<String>,
    pub last4: Option<String>,
    pub exp_month: Option<i16>,
    pub exp_year: Option<i16>,
    pub holder_name: Option<String>,
    pub billing_address_id: Option<i32>,
    pub status: i16,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::addresses::Entity",
        from = "Column::BillingAddressId",
        to = "super::addresses::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Addresses,
    #[sea_orm(
        belongs_to = "super::gateway_customers::Entity",
        from = "Column::GatewayCustomerId",
        to = "super::gateway_customers::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    GatewayCustomers,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::payment_setup_sessions::Entity")]
    PaymentSetupSessions,
    #[sea_orm(has_many = "super::payments::Entity")]
    Payments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addresses.def()
    }
}

impl Related<super::gateway_customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GatewayCustomers.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::payment_setup_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentSetupSessions.def()
    }
}

impl Related<super::payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
