//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "product_variant_options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub value: Option<String>,
    pub product_variant_id: i32,
    pub variant_option_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::ProductVariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProductVariants,
    #[sea_orm(
        belongs_to = "super::variant_options::Entity",
        from = "Column::VariantOptionId",
        to = "super::variant_options::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VariantOptions,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::variant_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VariantOptions.def()
    }
}
