//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "product_variants")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub sku: Option<String>,
    #[serde(with = "crate::utils::decimal::opt")]
    pub price: Option<Decimal>,
    #[serde(with = "crate::utils::decimal::opt")]
    pub cost_price: Option<Decimal>,
    #[serde(with = "crate::utils::decimal::opt")]
    pub compare_price: Option<Decimal>,
    pub inventory_quantity: i32,
    pub reserved_quantity: i32,
    pub track_inventory: bool,
    pub allow_backorder: bool,
    pub low_stock_threshold: i32,
    #[serde(with = "crate::utils::decimal::opt")]
    pub weight: Option<Decimal>,
    pub barcode: Option<String>,
    pub position: Option<i32>,
    pub active: Option<bool>,
    pub product_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cart_items::Entity")]
    CartItems,
    #[sea_orm(has_many = "super::order_items::Entity")]
    OrderItems,
    #[sea_orm(has_many = "super::product_variant_images::Entity")]
    ProductVariantImages,
    #[sea_orm(has_many = "super::product_variant_options::Entity")]
    ProductVariantOptions,
    #[sea_orm(has_many = "super::stock_reservations::Entity")]
    StockReservations,
    #[sea_orm(has_many = "super::stock_movements::Entity")]
    StockMovements,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Products,
}

impl Related<super::cart_items::Entity> for Entity {
    fn to() -> RelationDef { Relation::CartItems.def() }
}
impl Related<super::order_items::Entity> for Entity {
    fn to() -> RelationDef { Relation::OrderItems.def() }
}
impl Related<super::product_variant_images::Entity> for Entity {
    fn to() -> RelationDef { Relation::ProductVariantImages.def() }
}
impl Related<super::product_variant_options::Entity> for Entity {
    fn to() -> RelationDef { Relation::ProductVariantOptions.def() }
}
impl Related<super::stock_reservations::Entity> for Entity {
    fn to() -> RelationDef { Relation::StockReservations.def() }
}
impl Related<super::stock_movements::Entity> for Entity {
    fn to() -> RelationDef { Relation::StockMovements.def() }
}
impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef { Relation::Products.def() }
}
