//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "shipments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tracking_number: Option<String>,
    pub carrier: Option<String>,
    pub status: Option<i32>,
    pub shipped_at: Option<DateTime>,
    pub delivered_at: Option<DateTime>,
    pub order_id: i32,
    pub shipping_method_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::shipping_methods::Entity",
        from = "Column::ShippingMethodId",
        to = "super::shipping_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ShippingMethods,
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::shipping_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShippingMethods.def()
    }
}
