//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "shipping_methods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub code: Option<String>,
    pub base_price: Option<Decimal>,
    pub free_shipping_threshold: Option<Decimal>,
    pub active: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shipments::Entity")]
    Shipments,
}

impl Related<super::shipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shipments.def()
    }
}
