//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_movements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_variant_id: i32,
    pub order_id: Option<i32>,
    pub user_id: Option<i32>,
    #[sea_orm(column_type = "String(StringLen::N(30))")]
    pub r#type: String,
    pub quantity: i32,
    pub quantity_before: i32,
    pub quantity_after: i32,
    pub reference: Option<String>,
    pub notes: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::ProductVariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProductVariants,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Orders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef { Relation::ProductVariants.def() }
}
impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef { Relation::Orders.def() }
}
impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef { Relation::Users.def() }
}
