//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_reservations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_variant_id: i32,
    pub cart_id: Option<i32>,
    pub order_id: Option<i32>,
    pub quantity: i32,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::ProductVariantId",
        to = "super::product_variants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProductVariants,
    #[sea_orm(
        belongs_to = "super::carts::Entity",
        from = "Column::CartId",
        to = "super::carts::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Carts,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Orders,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef { Relation::ProductVariants.def() }
}
impl Related<super::carts::Entity> for Entity {
    fn to() -> RelationDef { Relation::Carts.def() }
}
impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef { Relation::Orders.def() }
}
